# -----------------------------------------------------------------
# Informazioni Progetto
# -----------------------------------------------------------------
site_name: "Documentazione CRI Venezia"
site_url: "https://docs.crivenezia.it" # URL CDN di Bunny
site_author: "CRI Comitato di Venezia"
site_description: "Documentazione interna e manuali per volontari e staff."

# -----------------------------------------------------------------
# Configurazione Tema (Material for MkDocs)
# -----------------------------------------------------------------
theme:
  name: material
  language: it

  # Aggiungi il percorso al logo (usando la variabile CDN)
  logo: 'https://crive.b-cdn.net/wp-content/uploads/2024/09/h60-scuro-1.png'
  favicon: '{{ config.extra.cdn_url }}/logos/favicon.ico'

  # Abilita la cartella per le sovrascritture
  custom_dir: src/overrides

  features:
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share

  # Palette Colori (SOLO LIGHT MODE)
  palette:
    scheme: default

  # Disattiva esplicitamente i link di editing
  repo_url: ""
  edit_uri: ""

# -----------------------------------------------------------------
# Caricamento CSS Extra
# -----------------------------------------------------------------
# Assumo che il percorso corretto sia docs/assets/css/cri.css (relativo a docs/)
extra_css:
  - assets/css/cri.css          # File principale
  - assets/css/home_cards.css   # File specifico per le card
  - assets/css/logo.css         # File specifico per il logo
  - assets/css/header.css       # File specifico per Header
  - assets/css/footer.css       # File specifico per Footer
  - assets/css/typesetting.css  # File specifico per testo
  - assets/css/box.css          # File specifico per i box

# -----------------------------------------------------------------
# Estensioni Markdown
# -----------------------------------------------------------------
markdown_extensions:
  admonition: {}
  pymdownx.details: {}
  pymdownx.superfences: {}
  pymdownx.caret: {}
  pymdownx.critic: {}
  pymdownx.mark: {}
  pymdownx.tilde: {}
  pymdownx.keys: {}
  pymdownx.tabbed:
      alternate_style: true
  attr_list: {}
  md_in_html: {}
  meta: {}
# -----------------------------------------------------------------
# Configurazione Plugin
# -----------------------------------------------------------------
plugins:
  search:
    lang: it
  awesome-nav:
    flatten_single_child_sections: false
  tags: {}
  git-revision-date-localized:
    type: date
  redirects:
    redirect_maps:
      # Cartella Cri Trasporti
      'cri-trasporti/compilazione-form/info_trasporto.md': 'cri-trasporti/compilazione-form/1_info_trasporto.md'
      'cri-trasporti/compilazione-form/dati_paziente.md': 'cri-trasporti/compilazione-form/3_dati_paziente.md'
      'cri-trasporti/compilazione-form/luogo_prelievo.md': 'cri-trasporti/compilazione-form/2_luogo_prelievo.md'
  glightbox:
    touchNavigation: true
    loop: false
    effect: zoom
    width: 100%
    height: auto
    zoomable: true
    draggable: true
    skip_classes:
      - skip-lightbox
    auto_caption: false
    caption_position: bottom
  macros: {}


# -----------------------------------------------------------------
# Variabili Extra (per il plugin Macros)
# -----------------------------------------------------------------
extra:
  cdn_url: "https://cridocs.b-cdn.net"
  social:
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/tuo-profilo/"
    - icon: "fontawesome/brands/facebook"
      link: "https://www.facebook.com/tuo-profilo/"
    - icon: "fontawesome/brands/instagram"
      link: "https://www.instagram.com/tuo-profilo/"