# -----------------------------------------------------------------
# Informazioni Progetto
# -----------------------------------------------------------------
site_name: "Documentazione CRI Venezia"
site_url: "https://cridocs.b-cdn.net" # URL CDN di Bunny
site_author: "CRI Comitato di Venezia"
site_description: "Documentazione interna e manuali per volontari e staff."

# -----------------------------------------------------------------
# Configurazione Tema (Material for MkDocs)
# -----------------------------------------------------------------
theme:
  name: material
  language: it

  # Aggiungi il percorso al logo (usando la variabile CDN)
  logo: '{{ config.extra.cdn_url }}/logos/logo-venezia.svg'
  favicon: '{{ config.extra.cdn_url }}/logos/favicon.ico'

  # Abilita la cartella per le sovrascritture
  custom_dir: src/overrides

  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    - navigation.instant
    - search.suggest
    - search.highlight
    - search.share
    # Le feature di editing sono disattivate da repo_url e edit_uri sotto

  # Palette Colori (SOLO LIGHT MODE)
  palette:
    scheme: default

  # Disattiva esplicitamente i link di editing
  repo_url: ""
  edit_uri: ""

# -----------------------------------------------------------------
# Struttura di Navigazione (Nav:)
# -----------------------------------------------------------------
# Awesome Pages prenderà il controllo, ma l'index deve essere definito.
nav:
  - Home: index.md
  # La sidebar verrà generata da .pages nelle sottocartelle
  - CRI-Corsi:
      - cri-plugins/cri-corsi/
  - CRI-Trasporti: cri-plugins/cri-trasporti/
  - Risorse Utili: risorse/

# -----------------------------------------------------------------
# Caricamento CSS Extra
# -----------------------------------------------------------------
# Assumo che il percorso corretto sia docs/assets/css/cri.css (relativo a docs/)
extra_css:
  - assets/css/cri.css

# -----------------------------------------------------------------
# Estensioni Markdown
# -----------------------------------------------------------------
markdown_extensions:
  admonition: {}
  pymdownx.details: {}
  pymdownx.superfences: {}
  pymdownx.caret: {}
  pymdownx.critic: {}
  pymdownx.mark: {}
  pymdownx.tilde: {}
  pymdownx.keys: {}
  pymdownx.tabbed:
      alternate_style: true
  attr_list: {}
  md_in_html: {}
  meta: {}
# -----------------------------------------------------------------
# Configurazione Plugin
# -----------------------------------------------------------------
plugins:
  search:
    lang: it
  awesome-pages: {}
  tags: {}
  git-revision-date-localized:
    type: date
  redirects: {}
  glightbox:
    touchNavigation: true
    loop: false
    effect: zoom
    width: 100%
    height: auto
    zoomable: true
    draggable: true
    skip_classes:
      - skip-lightbox
    auto_caption: false
    caption_position: bottom
  macros: {}


# -----------------------------------------------------------------
# Variabili Extra (per il plugin Macros)
# -----------------------------------------------------------------
extra:
  cdn_url: "https://cridocs.b-cdn.net"
  social:
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/tuo-profilo/"
    - icon: "fontawesome/brands/facebook"
      link: "https://www.facebook.com/tuo-profilo/"
    - icon: "fontawesome/brands/instagram"
      link: "https://www.instagram.com/tuo-profilo/"