sort:
  by: title

title: Manuali del Comitato
nav:
  # Puntiamo alla sottocartella /comunicazione/
  - Panoramica: index.md
  - Manuale Comunicazione: comunicazione/

  # In futuro potrai aggiungere:
  # - Manuale Logistica: logistica/
  # - Manuale Segreteria: segreteria_manuale/